### PR TITLE
Feat: Added event schedule / itinerary page

### LINKED ISSUE #6: Event Schedule Page
A page for the event schedule.

- [x] A timeline for event with titles
- [x] Event to be fetched from JSON ( Future reusability 😅)

### PR DESCRIPTION
**Pull request by SatyaRajAwasth1**
Resolves and closes #6.

Snapshot for on page load

snapshot for "to the page end"

### CODE REVIEW

**Comment by sujalbthapa** [comment]
The Dark Green and Light Yellow Should be nice from the figma file
tyo header baru would be good if we didn't add a seperate background but rather the title with the 3 lined underline from the home page EVENT HIGHLIGHTS section
ani can we remove the sponsors part ani make the register now button bigger

**Review by anishkn04 — CHANGES_REQUESTED** [review]
The title in `index.html` has been changed to `Document`, I suppose it was unintentional?

**Review by RishavOsaurus — COMMENTED** [review]
So I see you have used `<head class="m-0 box-border p-0">` but I don't think we are supposed to add any style to the `head` section?

**Comment by SatyaRajAwasth1** [comment]
> The title in `index.html` has been changed to `Document`, I suppose it was unintentional?

Actually, I have moved the index.html file to base directory from the /html directory, But, previously there was index file just with base syntax, thats why its showing that on the difference 😅

But, would love to change the title thanks for recommending.

@RishavOsaurus 

Quoting this too

> So I see you have used <head class="m-0 box-border p-0"> but I don't think we are supposed to add any style to the head section?

**Review by anishkn04 — APPROVED** [review]

**Review by RishavOsaurus — APPROVED** [review]

**Comment by SatyaRajAwasth1** [comment]
> The Dark Green and Light Yellow Should be nice from the figma file tyo header baru would be good if we didn't add a seperate background but rather the title with the 3 lined underline from the home page EVENT HIGHLIGHTS section ani can we remove the sponsors part ani make the register now button bigger

Gone over it and implemented as per design!

**Pull request merged**
