### PR TITLE
Updates to members and sponsors page

### PR DESCRIPTION
**Pull request by IntelligentBeaver**

### CODE REVIEW

**Comment by mukezhz** [comment]
@IntelligentBeaver please run 
`npm run format`
&
`npm run prod`

also fix the merge conflict

**Comment by mukezhz** [comment]
@IntelligentBeaver 
seems like `npm run prod` is missing

**Comment by IntelligentBeaver** [comment]
Ran `npm run format` and then `npm run prod` now.

**Review by mukezhz — APPROVED** [review]
LGTM 🔥

**Pull request merged**
